name: Container Build and Deploy

on: 
  push:
    branches: main
  workflow_dispatch:
    
env:
  AZURE_APP_NAME: everything-as-code-runtime
  IMAGE_NAME: everything-as-code-runtime:latest
  ACR_REGISTRY: ${{ secrets.ACR_REGISTRY }}
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      # - name: Deno Setup
      #   uses: denoland/setup-deno@v1
      #   with:
      #     deno-version: v1.45.5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.ACR_REGISTRY }}/${{ env.IMAGE_NAME }}
          file: DOCKERFILE
          context: .
          load: false
      
      - name: Deploy to Web App for Containers
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_APP_NAME }}
          images: ${{ env.ACR_REGISTRY }}/${{ env.IMAGE_NAME }}
